# Lectura de archivos

In [53]:
%matplotlib inline
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [54]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [55]:
id = '15eBo8goFc4q--lIGREc9Dknn9GqBybrs'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('test_values_selected_features_remix.csv')
test_values1 = pd.read_csv('test_values_selected_features_remix.csv', encoding='latin-1', index_col='building_id')
test_values1[test_values1.select_dtypes('O').columns] = test_values1[test_values1.select_dtypes('O').columns].astype('category')

In [56]:
id = '1F6ZTDoJc-aaiD-rpriXq5zmv2i84OSR4'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('train_values_selected_features_remix.csv')
train_values1 = pd.read_csv('train_values_selected_features_remix.csv', encoding='latin-1', index_col='building_id')
train_values1[train_values1.select_dtypes('O').columns] = train_values1[train_values1.select_dtypes('O').columns].astype('category')

In [57]:
id = '1kVPCXPedaMcZZIuj2wFjhJoQ36nD5kbq'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('train_values_complete_features_remix.csv')
train_values2 = pd.read_csv('train_values_complete_features_remix.csv', encoding='latin-1', index_col='building_id')
train_values2[train_values2.select_dtypes('O').columns] = train_values2[train_values2.select_dtypes('O').columns].astype('category')

In [58]:
id = '1XBWMAHR6sItnHT2dq3hX2nk9WrzNSF7J'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('test_values_complete_features_remix.csv')
test_values2 = pd.read_csv('test_values_complete_features_remix.csv', encoding='latin-1', index_col='building_id')
test_values2[test_values2.select_dtypes('O').columns] = test_values2[test_values2.select_dtypes('O').columns].astype('category')

In [59]:
id='1RUtolRcQlR3RGULttM4ZoQaK_Ouow4gc'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('train_labels.csv')
train_labels = pd.read_csv('train_labels.csv', encoding='latin-1', dtype={'building_id': 'int64', 'damage_grade': 'int64'}, index_col='building_id')

In [60]:
id = '1JDpXEXjP0QCLF7qbpMgWRdNCf5w3TURK'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('index.csv')

df_index = pd.read_csv('index.csv', encoding='latin-1', index_col='building_id')

# Ordenamiento

In [61]:
id = '1kt2VFhgpfRS72wtBOBy1KDat9LanfMZU'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('test_values.csv')

test_values = pd.read_csv('test_values.csv', encoding='latin-1', dtype = {'building_id': 'int64', 'geo_level_2_id': 'int64', 'geo_level_3_id': 'int64',\
                                                                           'count_floors_pre_eq': 'int64', 'age': 'int64', 'area_percentage': 'int64', \
                                                                           'height_percentage': 'int64', 'land_surface_condition': 'category',\
                                                                           'foundation_type': 'category', 'roof_type': 'category', 'ground_floor_type': 'category',\
                                                                           'other_floor_type': 'category', 'position': 'category', 'plan_configuration': 'category',\
                                                                           'has_superstructure_adobe_mud': 'boolean', 'has_superstructure_mud_mortar_stone': 'boolean', \
                                                                           'has_superstructure_stone_flag': 'boolean', 'has_superstructure_cement_mortar_stone': 'boolean',\
                                                                           'has_superstructure_mud_mortar_brick': 'boolean', 'has_superstructure_cement_mortar_brick': 'boolean',\
                                                                           'has_superstructure_timber': 'boolean', 'has_superstructure_bamboo': 'boolean',\
                                                                           'has_superstructure_rc_non_engineered': 'boolean', 'has_superstructure_rc_engineered': 'boolean',\
                                                                           'has_superstructure_other': 'boolean', 'legal_ownership_status': 'category', 'count_families': 'int64', \
                                                                           'has_secondary_use': 'boolean', 'has_secondary_use_agriculture': 'boolean', 'has_secondary_use_hotel': 'boolean', \
                                                                           'has_secondary_use_rental': 'boolean', 'has_secondary_use_institution': 'boolean', 'has_secondary_use_school': 'boolean',\
                                                                           'has_secondary_use_industry': 'boolean', 'has_secondary_use_health_post': 'boolean', \
                                                                           'has_secondary_use_gov_office': 'boolean', 'has_secondary_use_use_police': 'boolean', 'has_secondary_use_other': 'boolean'})

test_values2 = test_values2.reset_index()
test_values = test_values['building_id']
test_values = test_values.to_frame()
test_values2 = test_values.merge(test_values2, on = 'building_id').set_index('building_id')
df = train_values2.merge(train_labels, left_index = True, right_index= True)
train_values2 = df.drop(columns='damage_grade')
train_labels = pd.DataFrame(df['damage_grade'])

In [62]:
test_values = pd.read_csv('test_values.csv', encoding='latin-1', dtype = {'building_id': 'int64', 'geo_level_2_id': 'int64', 'geo_level_3_id': 'int64',\
                                                                           'count_floors_pre_eq': 'int64', 'age': 'int64', 'area_percentage': 'int64', \
                                                                           'height_percentage': 'int64', 'land_surface_condition': 'category',\
                                                                           'foundation_type': 'category', 'roof_type': 'category', 'ground_floor_type': 'category',\
                                                                           'other_floor_type': 'category', 'position': 'category', 'plan_configuration': 'category',\
                                                                           'has_superstructure_adobe_mud': 'boolean', 'has_superstructure_mud_mortar_stone': 'boolean', \
                                                                           'has_superstructure_stone_flag': 'boolean', 'has_superstructure_cement_mortar_stone': 'boolean',\
                                                                           'has_superstructure_mud_mortar_brick': 'boolean', 'has_superstructure_cement_mortar_brick': 'boolean',\
                                                                           'has_superstructure_timber': 'boolean', 'has_superstructure_bamboo': 'boolean',\
                                                                           'has_superstructure_rc_non_engineered': 'boolean', 'has_superstructure_rc_engineered': 'boolean',\
                                                                           'has_superstructure_other': 'boolean', 'legal_ownership_status': 'category', 'count_families': 'int64', \
                                                                           'has_secondary_use': 'boolean', 'has_secondary_use_agriculture': 'boolean', 'has_secondary_use_hotel': 'boolean', \
                                                                           'has_secondary_use_rental': 'boolean', 'has_secondary_use_institution': 'boolean', 'has_secondary_use_school': 'boolean',\
                                                                           'has_secondary_use_industry': 'boolean', 'has_secondary_use_health_post': 'boolean', \
                                                                           'has_secondary_use_gov_office': 'boolean', 'has_secondary_use_use_police': 'boolean', 'has_secondary_use_other': 'boolean'})

test_values1 = test_values1.reset_index()
test_values = test_values['building_id']
test_values = test_values.to_frame()
test_values1 = test_values.merge(test_values1, on = 'building_id').set_index('building_id')
df = train_values1.merge(train_labels, left_index = True, right_index= True)
train_values1 = df.drop(columns='damage_grade')
train_labels = pd.DataFrame(df['damage_grade'])

# Logistic Regression

In [63]:
train_values = train_values2.copy()
test_values = test_values2.copy()

## Continua la regresion

In [64]:
index = df_index.index
cols = train_values.index.tolist()
not_in_index = []
for col in cols: 
  if col not in index: not_in_index.append(col)

In [65]:
valid_values = train_values.loc[index]
train_values = train_values.loc[not_in_index]

valid_labels = train_labels.loc[index]
train_labels = train_labels.loc[not_in_index]

In [66]:
idx1 = train_values.shape[0]
idx2 = valid_values.shape[0]

In [67]:
data_df = pd.concat([train_values, valid_values, test_values], sort=False)

In [68]:
cat_features = ['geo_level_1_id', 'geo_level_2_id', 'geo_level_3_id', 'land_surface_condition',
                'foundation_type', 'roof_type', 'ground_floor_type', 'other_floor_type',
                'position', 'plan_configuration', 'legal_ownership_status',
                'count_families', 'range_age']
                    
num_features = ['count_floors_pre_eq', 'max_mean_area_percentage_id_1', 'mean_area_geo_level_1_id']

In [69]:
data_cat = pd.DataFrame(index = data_df.index, 
                  data = data_df,
                  columns = cat_features)

In [70]:
data_num = data_df.drop(columns = cat_features)
num_features = data_num.columns

In [71]:
data_num.shape

(347469, 169)

In [72]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

enc = OneHotEncoder(drop='first')
enc.fit(data_cat)

OneHotEncoder(categories='auto', drop='first', dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [73]:
data_cat_encoded = enc.transform(data_cat)

In [74]:
type(data_cat_encoded)

scipy.sparse.csr.csr_matrix

In [75]:
scaler = MinMaxScaler()
scaler.fit(data_num[:idx2])
data_num_scaled = scaler.transform(data_num)

In [76]:
type(data_num)

pandas.core.frame.DataFrame

In [77]:
data_cat_encoded

<347469x13351 sparse matrix of type '<class 'numpy.float64'>'
	with 3733351 stored elements in Compressed Sparse Row format>

In [78]:
from scipy.sparse import coo_matrix, hstack
data = hstack((data_cat_encoded,data_num_scaled))

In [79]:
data_cat_encoded

<347469x13351 sparse matrix of type '<class 'numpy.float64'>'
	with 3733351 stored elements in Compressed Sparse Row format>

In [80]:
data = data.astype(dtype='float16')

In [81]:
X_train = data.tocsr()[:idx1]
X_valid = data.tocsr()[idx1:idx2+idx1]
X_test = data.tocsr()[idx2+idx1:]

In [82]:
y_train = train_labels['damage_grade'].values
y_valid = valid_labels['damage_grade'].values

In [83]:
train_values = train_values.astype(dtype= {'geo_level_1_id': 'category', 'geo_level_2_id': 'category',
                                           'geo_level_3_id': 'category', 'count_families':'category', 
                                           'count_materials': 'category'})

test_values = test_values.astype(dtype= {'geo_level_1_id': 'category', 'geo_level_2_id': 'category',
                                           'geo_level_3_id': 'category', 'count_families':'category', 
                                           'count_materials': 'category'})

In [84]:
#idx = train_values.shape[0]
#data_df = pd.concat([train_values, test_values], sort=False)

#data_cat = pd.DataFrame(index = data_df.index, 
#                  data = data_df, 
#                  columns = cat_features)

#data_num = data_df.drop(columns = cat_features)

In [85]:
#data = data.astype(dtype='float16')
#X_train = data.tocsr()[:idx]
#X_test = data.tocsr()[idx:]

In [86]:
# para el undersample poner train_labels2
#y_train = train_labels['damage_grade']

In [87]:
#from sklearn.model_selection import train_test_split
#X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.3, random_state=9)

# Regresion

In [92]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(C = 0.9, verbose = 100, solver ='liblinear', max_iter=500, n_jobs=-1, random_state = 5)

In [93]:
log_reg.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))


[LibLinear]

LogisticRegression(C=0.9, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='auto', n_jobs=-1, penalty='l2', random_state=5,
                   solver='liblinear', tol=0.0001, verbose=100,
                   warm_start=False)

In [94]:
from sklearn.metrics import f1_score
# TEST SCORE
y_pred = log_reg.predict(X_valid)
f1_score(y_valid, y_pred, average='micro')

0.7434798736265844

In [95]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report

pred = y_pred
score = f1_score(y_valid, pred, average='micro')
#score = accuracy_score(y_valid_split, pred)

cm = confusion_matrix(y_valid, pred)
report = classification_report(y_valid, pred)

print("f1_micro: ", score, "\n\n")
print(cm, "\n\n")
print(report, "\n\n")

f1_micro:  0.7434798736265844 


[[ 3732  3624   145]
 [ 1626 37548  5273]
 [  184  9203 16846]] 


              precision    recall  f1-score   support

           1       0.67      0.50      0.57      7501
           2       0.75      0.84      0.79     44447
           3       0.76      0.64      0.69     26233

    accuracy                           0.74     78181
   macro avg       0.73      0.66      0.69     78181
weighted avg       0.74      0.74      0.74     78181
 




In [96]:
# TRAIN SCORE
y_pred = log_reg.predict(X_train)
f1_score(y_train, y_pred, average='micro')

0.7618682162043635

# Algunas cosas que se pueden probar; Tarda un rato largo el smote

## Si quiero hacer un SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=27)
X_train, y_train = sm.fit_sample(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


## Si quiero OverSampling

In [ ]:
pip install -U imbalanced-learn

     |████████████████████████████████| 206 kB 7.0 MB/s 
     |████████████████████████████████| 22.3 MB 1.4 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1
  Attempting uninstall: imbalanced-learn
    Found existing installation: imbalanced-learn 0.4.3
    Uninstalling imbalanced-learn-0.4.3:
      Successfully uninstalled imbalanced-learn-0.4.3


In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
sampling_strategy = "not majority"
ros = RandomOverSampler(sampling_strategy=sampling_strategy)
X_train, y_train = ros.fit_resample(X_train, y_train)

## SI quiero un undersampling

In [ ]:
from imblearn.under_sampling import RandomUnderSampler 

In [ ]:
sampling_strategy = "not minority"

rus = RandomUnderSampler(sampling_strategy=sampling_strategy)
X_train, y_train = rus.fit_resample(X_train, y_train)

# Ridge

In [ ]:
from sklearn.linear_model import RidgeClassifier
#penalty = 'l1'
ridge = RidgeClassifier(alpha= 10, max_iter=500, random_state = 5)

In [ ]:
ridge.fit(X_train, y_train)

RidgeClassifier(alpha=10, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=500, normalize=False, random_state=5, solver='auto',
                tol=0.001)

In [ ]:
from sklearn.metrics import f1_score
# TEST SCORE
y_pred = ridge.predict(X_valid)
f1_score(y_valid, y_pred, average='micro')

0.6869208188637977

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report

pred = y_pred
score = f1_score(y_valid, pred, average='micro')
#score = accuracy_score(y_valid_split, pred)

cm = confusion_matrix(y_valid, pred)
report = classification_report(y_valid, pred)

print("f1_micro: ", score, "\n\n")
print(cm, "\n\n")
print(report, "\n\n")

f1_micro:  0.6869208188637977 


[[ 4273   614   112]
 [ 5039 18682  5898]
 [  685  3970 12848]] 


              precision    recall  f1-score   support

           1       0.43      0.85      0.57      4999
           2       0.80      0.63      0.71     29619
           3       0.68      0.73      0.71     17503

    accuracy                           0.69     52121
   macro avg       0.64      0.74      0.66     52121
weighted avg       0.73      0.69      0.69     52121
 




In [ ]:
# TRAIN SCORE
y_pred = ridge.predict(X_train)
f1_score(y_train, y_pred, average='micro')

0.7799196448640144

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report

pred = y_pred
score = f1_score(y_train, pred, average='micro')
#score = accuracy_score(y_valid_split, pred)

cm = confusion_matrix(y_train, pred)
report = classification_report(y_train, pred)

print("f1_micro: ", score, "\n\n")
print(cm, "\n\n")
print(report, "\n\n")

f1_micro:  0.7799196448640144 


[[109313   7685   1642]
 [ 19091  77204  22345]
 [  4378  23190  91072]] 


              precision    recall  f1-score   support

           1       0.82      0.92      0.87    118640
           2       0.71      0.65      0.68    118640
           3       0.79      0.77      0.78    118640

    accuracy                           0.78    355920
   macro avg       0.78      0.78      0.78    355920
weighted avg       0.78      0.78      0.78    355920
 




In [ ]:
X_test.shape

(86868, 13402)

# Linear Discriminant

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis


In [ ]:
lda = LinearDiscriminantAnalysis()

In [ ]:
lda.fit(X_train.toarray(), y_train)

In [ ]:
from sklearn.metrics import f1_score
# TEST SCORE
y_pred = lda.predict(X_valid.to_array())
f1_score(y_valid, y_pred, average='micro')

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report

pred = y_pred
score = f1_score(y_valid, pred, average='micro')
#score = accuracy_score(y_valid_split, pred)

cm = confusion_matrix(y_valid, pred)
report = classification_report(y_valid, pred)

print("f1_micro: ", score, "\n\n")
print(cm, "\n\n")
print(report, "\n\n")

In [ ]:
# TRAIN SCORE
y_pred = ridge.predict(X_train)
f1_score(y_train, y_pred, average='micro')

0.7799196448640144

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report

pred = y_pred
score = f1_score(y_train, pred, average='micro')
#score = accuracy_score(y_valid_split, pred)

cm = confusion_matrix(y_train, pred)
report = classification_report(y_train, pred)

print("f1_micro: ", score, "\n\n")
print(cm, "\n\n")
print(report, "\n\n")

f1_micro:  0.7799196448640144 


[[109313   7685   1642]
 [ 19091  77204  22345]
 [  4378  23190  91072]] 


              precision    recall  f1-score   support

           1       0.82      0.92      0.87    118640
           2       0.71      0.65      0.68    118640
           3       0.79      0.77      0.78    118640

    accuracy                           0.78    355920
   macro avg       0.78      0.78      0.78    355920
weighted avg       0.78      0.78      0.78    355920
 




# Feature Selection

In [ ]:
import joblib
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

ModuleNotFoundError: ignored

In [ ]:
log_reg = LogisticRegression(C = 1.0, n_jobs=-1, random_state = 5)

sfs1 = sfs(log_reg,
           k_features=100,
           forward=True,
           floating=False,
           verbose=2,
           scoring='f1_micro',
           cv=3)

# Perform SFFS
sfs1 = sfs1.fit(X_train, y_train)
feat_cols = list(sfs1.k_feature_idx_)
print(feat_cols)


NameError: ignored

# Submission

In [104]:
probas = pd.DataFrame(log_reg.predict_proba(X_valid), index = valid_labels['damage_grade'].index, columns=['proba_1', 'proba_2', 'proba_3'])

In [105]:
y_predicted = log_reg.predict(X_valid)
probas['predicted_RL_7432'] = y_predicted
probas

proba_1   proba_2   proba_3  predicted_RL_7432
building_id                                                 
527621       0.002584  0.489651  0.507764                  3
117054       0.043553  0.826168  0.130279                  2
551897       0.281668  0.705987  0.012345                  2
959512       0.012834  0.862582  0.124585                  2
171542       0.008410  0.898496  0.093094                  2
...               ...       ...       ...                ...
787538       0.104885  0.659968  0.235146                  2
326651       0.157983  0.827703  0.014314                  2
681608       0.558882  0.396470  0.044648                  1
595490       0.014633  0.763857  0.221509                  2
802659       0.002345  0.433255  0.564399                  3

[78181 rows x 4 columns]

In [108]:
probas.to_csv('3_7432_RL_valid_probas.csv')

In [76]:
predicted_df = pd.DataFrame(y_pred.astype(np.int64), index = y_valid.index, columns=['damage_grade'])

In [ ]:
predicted_df.to_csv('mas_cortito.csv')

In [ ]:
from google.colab import files
files.download("mas_cortito.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>